name: first-workflow
on: 
  workflow_dispatch:
    inputs:
      target_repopath:
        description: "Repository name for the build"
        required: true
        default: "dockertest-docker"
      target_appname:
        description: "Application name"
        required: true
        default: "test"
      version_increment:
        description: "Version increment type"
        required: true
        type: choice
        options:
          - 'major'
          - 'minor'
          - 'patch'
        default: 'patch'

jobs:
  test:
    uses: alearning2554/githubactions-first/.github/workflows/test.yaml@main
    with:
      repopath: ${{ github.event.inputs.target_repopath }}
      appname: ${{ github.event.inputs.target_appname }}
      increment_type: ${{ github.event.inputs.version_increment }}